### ISSUE TITLE
[v1]: Escopo e tarefas

### ISSUE THREAD

**Issue by guesant** [guesant/friendly-tnsvue-migration-service-v0#1]
- check if nativescript is installed (`$ tns -v`)

# Tasks
- [x] before-init
  - [x] `$ git init`
  - [x] `$ git checkout -b" app-work "`
  - questions
     the answers will be stored in the `temp-migration-tool.json` file
    - [x] choose package manager (here we will call pmr)
    - [x] project paths
      - [x] app folder (src)
      - [x] entry point (main.js)
      - [x] appid (org.nativescript.application)
---
- [x] before-migrate
  - [x] `$ pmr run lint` (if it exists)
  - [x] `$ pmr add nativescript-vue`
  - [x] `$ pmr add @friendly-tnsvue/vue-plugin`

---
- [x] migrate
  - [x] update-files
    - [x] js
      - [x] update `import Vue from 'vue'` to` import Vue from' nativescript-vue'`
    - [x] vue-sfc
      - [x] update-template
        - [x] node-elements
          - [x] TEXT_NODE to ~`span`~ `p`
        ----
        - [x] semantic-tags
          - [x] header, main, footer -> `div`
          - [x] h1 -> `p`
          - [x] b, i -> ~`span`~ `p`
        ----
        - [x] convert-lstyles
          Use a preprocessor before, such as sass.
          - [x] Search for declarations like `display: ...; justify-content ... `and convert to object.
          - [x] Search for its element, and add the property `:lStyle="object"`
        ----
        - [x] template tags
          A component name using, by example, camelcase, will have lowercase text after parse. One solution is to go through the tags in the original template, and with a regexp, replace new content.
        ----
        - [x] rename-tags_cs - "cs" as _case sensitive_
          - [x] img -> `Image`
          - [x] iframe -> `WebView`
          - [x] button -> `Button`
            - [x] `[@click]` -> `[@tap]`
          ----
          - [x] input [type="checkbox"] -> `Switch`
          - [x] input [type="tel"]
            - [x] `[type]` => "phone"
          - [x] input [type="datetime-local"]
            - [x] `[type]` => "datetime"
          - [x] input [type: 'text', 'password', 'datetime', 'phone', 'number', 'url', 'email'] -> `TextField`
            - [x] `[value]` -> `[text]`
            - [x] `[placeholder]` -> `[hint]`
            - [x] `[type]` -> `[keyboardType]`

    - [x] vue-views
      - [x] Ask if want to add the `Page` component to the view folder files and/or select more files
  ----
  - [x] update-entry-point
    - [x] import `@friendly-tnsvue/vue-plugin` and add `Vue.use (...)`
    - [x] replace `.$mount('#app')` to `.$start()`
    - ~replace `h(App)` to `h('frame, [h (App)])`~
      - [ ] Ask if want to add the `Frame` component to the entry point file or `App.vue`
  ----
   - [x] update-package
      - [x] nativescript.id = appid;
  ---
  - [x] update-router
    _Install [nativescript-vue-navigator](https://github.com/nativescript-vue/nativescript-vue-navigator) if user wants._

---
- [x] finish
  - [x] update-paths
    - [x] Rename `entrypoint` to `app.js`
    - [x] Rename `srcfolder` to `app`

  ---
  - [x] template
    Copy template files
  ---
  - [x] clear-residual-files
    - [ ] ask if want to remove the `public` folder
    - [x] remove `temp-migration-tool.json`
  ---
  - [x] show additional info (run, help)

**Comment by guesant** [comment]
Issue será transferida para arquivo `docs/migration/v1.md`
